"""your message

Revision ID: 026cf01b010a
Revises: c0b6a8fd8824
Create Date: 2025-01-21 11:06:59.412606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026cf01b010a'
down_revision = 'c0b6a8fd8824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
