"""your message

Revision ID: 8cc9be32ce2e
Revises: 026cf01b010a
Create Date: 2025-01-21 11:14:03.124688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc9be32ce2e'
down_revision = '026cf01b010a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
